[theme]
# CarbonSeer - Modern professional color palette
primaryColor = "#FBA834"  # Vibrant orange
backgroundColor = "#F1F0E9"  # Warm fallback background
secondaryBackgroundColor = "#D4EBF8"  # Light blue
textColor = "#2C2C2C"  # Dark charcoal text
font = "sans serif"

[server]
headless = true
port = 8501
# address = "0.0.0.0"
# enableCORS = false
# enableXsrfProtection = false
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"
