[theme]
# Inspired by carbon footprint tracker design - soft, elegant, earthy tones
primaryColor = "#8B7D9B"  # Muted purple from moodboard
backgroundColor = "#F5F3F0"  # Soft beige background
secondaryBackgroundColor = "#FFFFFF"  # Clean white cards
textColor = "#2C2C2C"  # Dark charcoal text
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true
toolbarMode = "minimal"
